export const menuOptions = [
  {
    id: 1,
    name: "Lični",
    description: "Lični raspored za tekući mesec",
    menu: "Raspored",
  },
  {
    id: 2,
    name: "Timski",
    description: "Timski raspored za tekući mesec",
    menu: "Raspored",
  },
  {
    id: 3,
    name: "Odeljenski",
    description: "Pregled svih timskih rasporeda za tekući mesec",
    menu: "Raspored",
  },
  {
    id: 4,
    name: "Smenski",
    description: "Brzi pregled svih tehničara u timu po datumu i smeni",
    menu: "Raspored",
  },
  {
    id: 5,
    name: "Kreiraj",
    description: "Kreiranje rasporeda za naredni mesec za sve timove",
    menu: "Raspored",
  },
  {
    id: 6,
    name: "Lista",
    description: "Lista postojećih timova",
    menu: "Timovi",
  },
  {
    id: 7,
    name: "Dodaj",
    description: "Dodavanje novog tima",
    menu: "Timovi",
  },
  {
    id: 8,
    name: "Izmeni",
    description: "Izmena postojećeg tima",
    menu: "Timovi",
  },
  {
    id: 9,
    name: "Obriši",
    description: "Brisanje postojećeg tima",
    menu: "Timovi",
  },
  {
    id: 10,
    name: "Lista",
    description: "Spisak svih zaposlenih",
    menu: "Zaposleni",
  },
  {
    id: 11,
    name: "Dodaj",
    description: "Dodaj novog zaposlenog",
    menu: "Zaposleni",
  },
  {
    id: 12,
    name: "Izmeni",
    description: "Izmena podataka zaposlenih",
    menu: "Zaposleni",
  },
  {
    id: 13,
    name: "Obriši",
    description: "Obriši zaposlenog - podaci se arhiviraju!",
    menu: "Zaposleni",
  },
  {
    id: 14,
    name: "Pretraga",
    description: "Pretraga zaposlenih po različitim kriterijumima",
    menu: "Zaposleni",
  },
  {
    id: 15,
    name: "Aplikacija",
    description: "Podešavanja izgleda i funkcionalnosti aplikacije",
    menu: "Podešavanja",
  },
  {
    id: 16,
    name: "Administracija",
    description: "Administrativna podešavanja aplikacije i podataka",
    menu: "Podešavanja",
  },
  {
    id: 17,
    name: "Timovi",
    description: "Podešavanja organizacije timova",
    menu: "Podešavanja",
  },
  {
    id: 18,
    name: "Prikaz",
    description: "Prikaz osnovnih podataka korisnika",
    menu: "Profil",
  },
  {
    id: 19,
    name: "Izmena",
    description: "Izmena osnovnih podataka korisnika",
    menu: "Profil",
  },
  {
    id: 20,
    name: "Izmeni",
    description: "Izmeni podatke u zaglavlju izabranog rasporeda",
    menu: "RCZaglavlje",
  },
  {
    id: 21,
    name: "Dodaj/promeni ulogu",
    description: "Dodavanje / promena uloge u sklopu tima",
    menu: "RCImeClana",
  },
  {
    id: 22,
    name: "Prebaci u drugi tim",
    description: "Prebacivanje zaposlenog u drugi tim",
    menu: "RCImeClana",
  },
  {
    id: 23,
    name: "Dodaj smenu",
    description: "Dodavanje smene zaposlenom",
    menu: "RCSmena",
  },
  {
    id: 24,
    name: "Promeni smenu",
    description: "Promena tipa smene",
    menu: "RCSmena",
  },
  {
    id: 25,
    name: "Obriši smenu",
    description: "Brisanje smene sa rasporeda",
    menu: "RCSmena",
  },
  {
    id: 26,
    name: "Dodeli smenu",
    description: "Dodela smene za ceo tim",
    menu: "RCDatumSmene",
  },
  {
    id: 27,
    name: "Izmeni smenu",
    description: "Izmena smene za ceo tim",
    menu: "RCDatumSmene",
  },
  {
    id: 28,
    name: "Obriši smenu",
    description: "Brisanje smene za ceo tim",
    menu: "RCDatumSmene",
  },
];
